version: '3.8'
services:
  db:
    container_name: pump_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: workout
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
networks:
  local: